# this build injects security configurations into deployer
# see https://www.baeldung.com/deploy-to-jetty
version: "3.2"

volumes:
  data-jetty-files: {}
  data-jetty-logs: {}

services: 
    # rest simulator app runs on http://localhost:8080/
    # deployer runs on http://localhost:8080/cargo-jetty-deployer/

    restsimulator :
        build: .
        ports: 
          - "8080:8080"
        volumes:
          # setting up log data storage (target is used in log4j2.xml)
          - data-jetty-logs:/var/lib/jetty/target
          # setting up data files storage
          - data-jetty-files:/data-jetty-files
          # setting up poperties for restsimulator app
          - ./container-fs/jetty/start.d/restsimulator.ini:/var/lib/jetty/start.d/restsimulator.ini
          
          # setting up security for cargo-deployer
          - ./container-fs/jetty/webapps/cargo-deployer/WEB-INF/web.xml:/var/lib/jetty/webapps/cargo-deployer/WEB-INF/web.xml
          - ./container-fs/jetty/webapps/cargo-deployer/WEB-INF/jetty-web.xml:/var/lib/jetty/webapps/cargo-deployer/WEB-INF/jetty-web.xml
          - ./container-fs/jetty/etc/realm.properties:/usr/local/jetty/etc/realm.properties
      


